server:
  port: 8081

spring:
  mongodb:
    host: mongo-stage
    port: 27017
    database: userdb_stage

logging:
  level:
    root: WARN
    com.subham.ordermanagement: WARN

  file:
    name: /logs/user-service-stage.log