server:
  port: 8081

spring:
  mongodb:
    host: mongo-dev
    port: 27017
    database: userdb_dev


logging:
  level:
    root: DEBUG
    com.subham.ordermanagement: DEBUG

  file:
    name: /logs/user-service-dev.log