server:
  port: 8081

spring:
  mongodb:
    host: mongo-prod
    port: 27017
    database: userdb_prod

logging:
  level:
    root: ERROR
    com.subham.ordermanagement: ERROR

  file:
    name: /logs/user-service-prod.log