server:
  port: 8081

spring:
  application:
    name: user-service

  mongodb:
    host: localhost       # Docker service name
    port: 27017
    database: userdb


logging:
  file:
    path: /logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha




