server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  user-service:
    url: http://localhost:8081/api/v1/users/getUser

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 5
        failureRateThreshold: 30
        waitDurationInOpenState: 5s

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
