server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  user-service:
    url: http://user-service:8081/api/v1/users/getUser

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

logging:
  level:
    root: INFO
