server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-stage:5432/orderdb_stage
    username: postgres_stage
    password: postgres_stage
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  user-service:
    url: http://user-service.stage.internal/api/v1/users/getUser

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 20
        failureRateThreshold: 40
        waitDurationInOpenState: 15s

logging:
  level:
    root: WARN
    com.subham.ordermanagement: WARN

  file:
    name: /logs/order-service-stage.log
