server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-prod:5432/orderdb_prod
    username: postgres_prod
    password: postgres_prod
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  user-service:
    url: http://user-service.prod.svc.cluster.local/api/v1/users/getUser

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 50
        failureRateThreshold: 20
        waitDurationInOpenState: 30s

logging:
  level:
    root: ERROR
    com.subham.ordermanagement: ERROR

  file:
    name: /logs/order-service-prod.log
