server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-stage:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  user-service:
    url: http://user-service-stage:8081/api/v1/users/getUser

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 20
        failureRateThreshold: 40
        waitDurationInOpenState: 15s

logging:
  level:
    root: WARN
    com.subham.ordermanagement: WARN

  file:
    name: /logs/order-service-stage.log
